config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app
    match '/auth/google' => 'auth#index', :as => :authorize_google_docs, :defaults => {:provider => 'google'}

    resources :google_docs do
      get :search, :on => :collection
    end

    match '/i18n/environment.js' => 'javascripts#environment', :as => :javascript_environment

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_new(.:format)' => 'activities#show_new', :as => :show_new, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        put :transfer
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_new(.:format)' => 'activities#show_new', :as => :show_new, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
      resources :uploads
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :projects, :except => [:new, :edit] do
        member do
          put :transfer
        end

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

        resources :invitations, :except => [:new, :edit, :update] do
          member do
            put :resend
          end
        end

        resources :task_lists, :except => [:new, :edit] do
          member do
            put :archive
            put :unarchive
          end

          resources :tasks, :except => [:new, :edit]
        end

        resources :tasks, :except => [:new, :edit, :create] do
          member do
            put :watch
            put :unwatch
          end

          resources :comments, :except => [:new, :edit]
        end

        resources :uploads, :except => [:new, :edit, :update]

        resources :pages, :except => [:new, :edit] do
          collection do
            put :resort
          end

          member do
            put :reorder
          end
        end

        resources :notes, :except => [:new, :edit]

        resources :dividers, :except => [:new, :edit]

        match 'search' => 'search#index', :as => :search
      end

      resources :activities, :only => [:index, :show]

      resources :invitations, :except => [:new, :edit, :update, :create] do
        member do
          put :accept
        end

app/views/shared/_gantt_banner_primer.haml
#gantt_banner.banner_item{:style => "#{ 'display: none' unless current_gantt_view?(:gantt)}"}
  .primer=t('.title')

app/views/shared/_global_navigation.haml
#user_utilities
  %ol.global_navigation
    /= micro_avatar(current_user)
    %li= link_to current_user.login, current_user
    %li= link_to t('.settings'), account_settings_path
    - if current_user.invitations.pending_projects.count > 0
      %li= link_to_unless_current t('.project_invitations', :count => current_user.invitations.count),
        user_invitations_path(:user_id => current_user.id)
    %li= link_to t('.help'), "http://guide.teambox.com##{controller_name}", :target => "_blank"
    %li= link_to t('.logout'), logout_path

app/views/shared/_header.html.haml
.header
  %h1= link_to logo_image, projects_path
  = search_bar
  = render 'shared/global_navigation'

app/views/shared/_latest_announcement.haml
- if t('latest_announcement_html').length > 5
  .box
    %p= t('latest_announcement_html')

app/views/shared/_navigation.m.haml
#menubar
  = link_to t('shared.project_navigation.overview'), activities_path, :class => (controller.controller_name == 'activities' ? 'selected' : '')
  = link_to t('shared.navigation.all_projects'), projects_path, :class => (controller.controller_name == 'projects' && !@current_project ? 'selected' : '')
  - if @current_project
    = link_to h(@current_project), project_path(@current_project), :class => (@current_project ? 'selected' : '')
  = #link_to "My tasks"

app/views/shared/_project_navigation.m.haml
#page_menu
  = link_to t('shared.project_navigation.conversations'), project_conversations_path(project), :class => controller_selected?('conversations')
  = link_to t('shared.project_navigation.task_lists'), project_task_lists_path(project), :class => controller_selected?(['task_lists', 'tasks'])
  = link_to t('shared.project_navigation.pages'), project_pages_path(project), :class => controller_selected?('pages')
  -# = link_to t('shared.project_navigation.files'), project_uploads_path(project), :class => controller_selected?('uploads')
  = link_to t('shared.project_navigation.people'), project_people_path(project), :class => controller_selected?('people')

app/views/shared/_search_bar.haml
- if current_user.can_search? or (@current_project && @current_project.user.can_search?)
  .search_bar
    - per_project = !current_user.can_search?
    - search_destination = per_project ? project_search_path(@current_project) : search_path
    - form_tag search_destination, :method => 'get', :class => 'search', :id => 'search' do
      = text_field_tag :q, nil, :type => 'search', :id => nil,
        :placeholder => per_project ? t('search.placeholder_in_project') : t('search.placeholder')
      - if per_project
        = hidden_field_tag :project_id, @current_project

app/views/shared/_submit_or_cancel.haml
= loading_image(loading_id)

.submit{ :id => submit_id }
  = submit_tag h(name), :class => (object.new_record? ? "inline_form_create" : "inline_form_update")
  = t('common.or')
  = link_to t('form.cancel'), "#", :class => (object.new_record? ? "inline_form_create_cancel" : "inline_form_update_cancel")

app/views/shared/_upcoming_events.haml
- style = current_gantt_view?(:calendar)? '' : 'display: none'
#upcoming_events_banner.upcoming_events_banner.banner_item{:style => style}
  %table
    - for table_row in [(0..6),(7..13),(14..20),(21..27)]
      %tr
        - for i in table_row
          %th{ :class => event_css(i) }
            = (Date.today.monday + i.day).strftime("%a %e")
      %tr.days_events
        - for i in table_row
          %td{ :class => event_css(i) }
            = render 'shared/event', :events => events[i]

app/views/shared/_upcoming_events_primer.haml
#upcoming_events_banner.banner_item{:style => "#{'display: none' unless current_gantt_view?(:calendar)}"}
  .primer=t('.title')

app/views/shared/_upgrade_browser.haml
/[if lte IE 7]
  %div{ :style => "border:3px solid #090; margin:8px 0; background:#cfc; color:#000; width:345px; padding: 5px" }
    = t('.upgrade')
    = link_to t('.ie'), "http://www.microsoft.com/windows/Internet-explorer"
    = t('.or_install')
    = link_to t('.chrome'), "http://google.com/chrome"
    = link_to t('.firefox'), "http://getfirefox.com"
    = t('common.or')
    = link_to t('.safari'), "http://apple.com/safari"

app/views/shared/_watchers.html.haml
.watching#watching
  = watch_link(project,user,target)
  - if target.watchers.empty?
    = t('.nobody_watching')
  - else
    = t('.people_watching')
    = target.watchers.collect {|u| h(u) }.to_sentence
  - case state
    - when :started_watching
      %span.state.started#updated_watch_state= t('.started_watching')
    - when :stopped_watching
      %span.state.stopped#updated_watch_state= t('.stopped_watching')
      

app/views/shared/_watchers.m.haml
.watching#watching
  - if target.watchers.empty?
    = t('.nobody_watching')
  - else
    = t('.people_watching')
    = target.watchers.collect {|u| h(u) }.to_sentence
  = watch_link(project,user,target)

app/views/shared/iframe_error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
  </head>
  <body class="error"><script type="application/x-json"><%= data.to_json %></script></body>
</html>