config/routes.rb
Teambox::Application.routes.draw do

  # If secure_logins is true, constrain matches to ssl requests
  class SSLConstraints
    def self.matches?(request)
      !Teambox.config.secure_logins || request.ssl?
    end
  end

  resources :sites, :only => [:show, :new, :create]

  match '/public' => 'public/projects#index', :as => :public_projects

  namespace :public do
    match ':id' => 'projects#show', :as => :project
    match ':project_id/conversations' => 'conversations#index', :as => :project_conversations
    match ':project_id/conversations/:id' => 'conversations#show', :as => :project_conversation
    match ':project_id/:id' => 'pages#show', :as => :project_page
  end

  match 'api' => 'apidocs#index', :as => :api
  match 'api/concepts' => 'apidocs#concepts', :as => :api_concepts
  match 'api/routes' => 'apidocs#routes', :as => :api_routes
  match 'api/changes' => 'apidocs#changes', :as => :api_changes
  match 'api/:model' => 'apidocs#model', :as => :api_model

  resources :sprockets, :only => [:index, :show]

  #Constrain all requests to the ssl constraint
  scope :constraints => SSLConstraints do

    match '/logout' => 'sessions#destroy', :as => :logout
    match '/login' => 'sessions#new', :as => :login
    match '/login/:username' => 'sessions#backdoor', :as => :login_backdoor if Rails.env.cucumber?

    match '/register' => 'users#create', :as => :register
    match '/signup' => 'users#new', :as => :signup

    match '/search' => 'search#index', :as => :search

    match '/text_styles' => 'users#text_styles', :as => :text_styles
    match '/invite_format' => 'invitations#invite_format', :as => :invite_format
    match '/feeds' => 'users#feeds', :as => :feeds
    match '/calendars' => 'users#calendars', :as => :calendars
    match '/disable_splash' => 'users#disable_splash', :as => :disable_splash
    match '/forgot' => 'reset_passwords#new', :as => :forgot_password
    match '/reset/:reset_code' => 'reset_passwords#reset', :as => :reset_password
    match '/forgetting' => 'reset_passwords#update_after_forgetting', :as => :update_after_forgetting, :method => :put
    match '/reset_password_sent' => 'reset_passwords#sent', :as => :sent_password

    match '/format/:f' => 'sessions#change_format', :as => :change_format

    match '/projects/:project_id/invite/:login' => 'invitations#create', :as => :create_project_invitation, :method => :post

    match '/auth/:provider/callback' => 'auth#callback', :as => :auth_callback
    match '/auth/failure' => 'auth#failure', :as => :auth_failure
    match '/complete_signup' => 'users#complete_signup', :as => :complete_signup
    match '/auth/:provider/unlink' => 'users#unlink_app', :as => :unlink_app
    match '/auth/google' => 'auth#index', :as => :authorize_google_docs, :defaults => {:provider => 'google'}

    resources :google_docs do
      get :search, :on => :collection
    end

    match '/i18n/environment.js' => 'javascripts#environment', :as => :javascript_environment

    #RAILS 3 Useless resource?
    resources :reset_passwords
    resource :session

    resources :organizations do
      member do
        get :projects
        get :external_view
        get :delete
        get :appearance
      end
      resources :memberships do
        member do
          get :change_role
          get :add
          get :remove
        end
      end
    end

    match '/account/settings' => 'users#edit', :as => :account_settings, :sub_action => 'settings'
    match '/account/picture' => 'users#edit', :as => :account_picture, :sub_action => 'picture'
    match '/account/profile' => 'users#edit', :as => :account_profile, :sub_action => 'profile'
    match '/account/linked_accounts' => 'users#edit', :as => :account_linked_accounts, :sub_action => 'linked_accounts'
    match '/account/notifications' => 'users#edit', :as => :account_notifications, :sub_action => 'notifications'
    match '/account/delete' => 'users#edit', :as => :account_delete, :sub_action => 'delete'
    match '/account/destroy' => 'users#destroy', :as => :destroy_user
    match '/account/activity_feed_mode/collapsed' => 'users#change_activities_mode', :as => :collapse_activities, :collapsed => true
    match '/account/activity_feed_mode/expanded' => 'users#change_activities_mode', :as => :expand_activities, :collapsed => false

    resources :teambox_datas, :path => '/datas' do
      member do
        get :download
      end
    end

    resources :users do
      resources :invitations
      member do
        get :confirm_email
        get :unconfirmed_email
        get :contact_importer
      end
      resources :conversations
      resources :task_lists do
        resources :tasks
      end
      match 'activities/users/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    end

    match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
    match 'activities/:id/show_new(.:format)' => 'activities#show_new', :as => :show_new, :method => :get
    match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
    match 'activities/:id/show_thread(.:format)' => 'activities#show_thread', :as => :show_thread, :method => :get

    match 'projects/archived.:format' => 'projects#index', :as => :project_archived, :sub_action => 'archived'

    match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

    resources :projects do
      member do
        post :accept
        post :decline
        put :transfer
        get :join
      end

      match 'time/:year/:month' => 'hours#index', :as => :hours_by_month, :via => :get
      match 'time/by_period' => 'hours#by_period', :as => :hours_by_period, :via => :get
      match 'time' => 'hours#index', :as => :time
      match 'settings' => 'projects#edit', :as => :settings, :sub_action => 'settings'
      match 'picture' => 'projects#edit', :as => :picture, :sub_action => 'picture'
      match 'deletion' => 'projects#edit', :as => :deletion, :sub_action => 'deletion'
      match 'ownership' => 'projects#edit', :as => :ownership, :sub_action => 'ownership'

      resources :invitations do
        member do
          put :accept
          put :decline
          get :resend
        end
      end

      match 'activities(.:format)' => 'activities#show', :as => :activities, :method => :get
      match 'activities/:id/show_new(.:format)' => 'activities#show_new', :as => :show_new, :method => :get
      match 'activities/:id/show_more(.:format)' => 'activities#show_more', :as => :show_more, :method => :get
      resources :uploads
      match 'hooks/:hook_name' => 'hooks#create', :as => :hooks, :via => :post

      match 'invite_people' => 'projects#invite_people', :as => :invite_people, :via => :get
      match 'invite_people' => 'projects#send_invites', :as => :send_invites, :via => :post

      resources :tasks do
        member do
          put :reorder
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :task_lists do
        collection do
          get :gantt_view
          get :archived
          put :reorder
        end
        member do
          put :archive
          put :unarchive
          put :watch
          put :unwatch
        end

        resources :tasks do
          member do
            put :watch
            put :unwatch
          end

          resources :comments
        end
      end

      match 'contacts' => 'people#contacts', :as => :contacts, :method => :get

      resources :people do
        member do
          get :destroy
        end
      end

      resources :conversations do
        member do
          put :convert_to_task
          put :watch
          put :unwatch
        end

        resources :comments
      end

      resources :pages do
        collection do
          post :resort
        end
        member do
          post :reorder
        end
        # In rails 2, we have :pages, :has_many => :task_list ?!
        resources :notes,:dividers,:uploads
      end

      match 'search' => 'search#index', :as => :search

      resources :google_docs do
        collection do
          :search
        end
      end
    end

    namespace :api_v1, :path => 'api/1' do
      resources :projects, :except => [:new, :edit] do
        member do
          put :transfer
        end

        resources :activities, :only => [:index, :show]

        resources :people, :except => [:create, :new, :edit]

        resources :comments, :except => [:new, :create, :edit]

        resources :conversations, :except => [:new, :edit] do
          member do
            put :watch
            put :unwatch
            post :convert_to_task
          end

          resources :comments, :except => [:new, :edit]
        end

        resources :invitations, :except => [:new, :edit, :update] do
          member do
            put :resend
          end
        end

        resources :task_lists, :except => [:new, :edit] do
          member do
            put :archive
            put :unarchive
          end

          resources :tasks, :except => [:new, :edit]
        end

        resources :tasks, :except => [:new, :edit, :create] do
          member do
            put :watch
            put :unwatch
          end

          resources :comments, :except => [:new, :edit]
        end

        resources :uploads, :except => [:new, :edit, :update]

        resources :pages, :except => [:new, :edit] do
          collection do
            put :resort
          end

          member do
            put :reorder
          end
        end

        resources :notes, :except => [:new, :edit]

        resources :dividers, :except => [:new, :edit]

        match 'search' => 'search#index', :as => :search
      end

      resources :activities, :only => [:index, :show]

      resources :invitations, :except => [:new, :edit, :update, :create] do
        member do
          put :accept
        end

app/models/user/authentication.rb
class User
  
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  
  def self.authenticate(login, password)
    unless login.blank? or password.blank?
      u = find_by_username_or_email(login)
      u && u.authenticated?(password) ? u : nil
    end
  end

end

app/models/user/roles.rb
class User
  
  def observable?(user)
    projects_shared_with(user).any? || user == self
  end
  
  def can_search?
    Teambox.config.allow_search
  end
  
end

app/controllers/api_v1/users_controller.rb
class ApiV1::UsersController < ApiV1::APIController
  before_filter :find_user, :only => [ :show ]
  skip_before_filter :load_project
  
  def index
    api_respond current_user.users_with_shared_projects, :references => []
  end

  def show
    projects_shared = @user.projects_shared_with(@current_user)
    shares_invited_projects = projects_shared.empty? && @user.shares_invited_projects_with?(@current_user)
    
    if @user != @current_user and (!shares_invited_projects and projects_shared.empty?)
      api_error(:unauthorized, :type => 'InsufficientPermissions', :message => t('users.activation.invalid_user'))
    else
      api_respond @user
    end
  end
  
  def current
    api_respond current_user, :include => api_include+[:email]
  end

  protected
  
  def find_user
    unless @user = (User.find_by_login(params[:id]) || User.find_by_id(params[:id]))
      api_error(:not_found, :type => 'ObjectNotFound', :message => t('not_found.user'))
    end
  end
  
  def api_include
    [:projects, :organizations] & (params[:include]||{}).map(&:to_sym)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper

  def user_link(user)
    if user.name.blank?
      link_to user.login, user_path(user)
    else
      link_to h(user.name), user_path(user)
    end
  end

  def show_user_password_fields
    update_page do |page|
      page['change_password_link'].hide
      page['password_fields'].show
      page['user_password'].focus
    end
  end
  
  def user_rss_token(url, filter = nil)
    filter_param = filter.present? ? "&filter=#{filter}" : ""
    url + "?rss_token=#{current_user.rss_token}#{current_user.id}#{filter_param}"
  end
  
  def avatar_or_gravatar(user, size)
    user.avatar_or_gravatar_path(size, request.ssl?).tap do |url|
      unless url.starts_with? 'http'
        url.replace(root_url.chomp('/') + url)
        url.sub! 'http:', 'https:' if request.ssl?
      end
    end
  end
  
  def gravatar_url
    "<a href='http://gravatar.com'>Gravatar</a>".html_safe
  end
  
  def build_user_phone_number(user)
    card = user.card || user.build_card
    card.phone_numbers.build unless card.phone_numbers.any?
  end
  
  def load_javascript_user_data
    javascript_tag %(
      my_user = #{json_user}
      my_projects = #{json_people}
      current_project = #{@current_project ? @current_project.id : 'null'}
    )
  end
  
  def load_my_avatar_for_new_comments
    %(<style type='text/css'>
        a.micro_avatar.my_avatar { background: url(#{avatar_or_gravatar(current_user, :micro)}) no-repeat }
      </style>).html_safe
  end

  def js_for_signup_form_validations
    error_messages = 
      %w(too_long too_short empty invalid confirmation).inject({}) do |r,key|
        r[key] = t("activerecord.errors.messages.#{key}")
        r
      end
    strength_messages =
      %w(too_short weak average strong too_long).inject({}) do |r,key|
        r[key] = t("password_strength.#{key}")
        r
      end

    javascript_tag <<-EOS
    var FieldMessages = (#{error_messages.to_json})
    var StrengthMessages = (#{strength_messages.to_json})
    var FieldErrors = {
      add: function(input, message) {
        input.up('div').addClassName('field_with_errors')
        input.up('.text_field').down('.errors_for').innerHTML = message
        this.setSuccess(input, false)
      },
      clear: function(input) {
        if (input.up('.field_with_errors'))
          input.up('.field_with_errors').removeClassName('field_with_errors')
        input.up('.text_field').down('.errors_for').innerHTML = ""
        this.setSuccess(input, true)
      },
      setSuccess: function(input, status) {
        var icon = input.up('.text_field').down('.result_icon')
        if (!icon) {
          var icon = new Element('div', { 'class': 'result_icon' })
          input.insert({after: icon})
        }
        icon.className = 'result_icon ' + (status ? 'static_tick_icon' : 'static_cross_icon')
      },
      displayStrength: function(input) {
        this.clear(input);
        var password = input.value
        var score = 0;
        if (password.match(/[!,@,#,$,%,^,&,*,?,_,~]/)) score += 1;
        if (password.match(/([a-z])/)) score += 1;
        if (password.match(/([A-Z])/)) score += 1;
        if (password.match(/([0-9])/)) score += 1;
        if (password.length >= 8) score += 2;
        if (password.length >= 10) score += 2;

        var strength = "average";
        if (score < 3) strength = "weak";
        if (score > 5) strength = "strong";

        var message_field = input.up('.text_field').down('.errors_for');
        message_field.innerHTML = StrengthMessages[strength];
        message_field.className = "errors_for "+strength
      }
    }

    document.on('change', '#user_first_name, #user_last_name', function(e,input) {
      if(input.value.length > 20) {
        FieldErrors.add(input, FieldMessages.too_long.gsub('%{count}',20))
      } else if (input.value.length < 1) {
        FieldErrors.add(input, FieldMessages.empty)
      } else {
        FieldErrors.clear(input)
      }
    })

    document.on('change', '#user_login', function(e,input) {
      if(!input.value.match(/^[a-z0-9_]+$/i)) {
        FieldErrors.add(input, FieldMessages.invalid)
      } else if (input.value.length > 40) {
        FieldErrors.add(input, FieldMessages.too_long.gsub('%{count}',40))
      } else if (input.value.length < 3) {
        FieldErrors.add(input, FieldMessages.too_short.gsub('%{count}',3))
      } else {
        FieldErrors.clear(input)
      }
    })

    document.on('change', '#user_email', function(e,input) {
      if(!input.value.match(/^[\\w\\.%\\-]+@(?:[A-Z0-9\\-]+\\.)+(?:[A-Z]{2,3}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|coop|museum)$/i)) {
        FieldErrors.add(input, FieldMessages.invalid)
      } else if (input.value.length > 100) {
        FieldErrors.add(input, FieldMessages.too_long.gsub('%{count}',100))
      } else {
        FieldErrors.clear(input)
      }
    })

    document.on('keydown', '#user_password', function(e,input) {
      if (input.value.length < 6) {
        FieldErrors.add(input, StrengthMessages.too_short.gsub('%{count}',6))
      } else if (input.value.length > 40) {
        FieldErrors.add(input, StrengthMessages.too_long.gsub('%{count}',40))
      } else {
        FieldErrors.displayStrength(input)
      }
    }.debounce(200))

    document.on('keydown', '#user_password_confirmation', function(e,input) {
      if(input.value != $('user_password').value) {
        FieldErrors.add(input, FieldMessages.confirmation)
      } else {
        FieldErrors.clear(input)
      }
    }.debounce(200))
    EOS
  end

  protected

    def json_user
      {
        :id => current_user.id,
        :username => current_user.login, 
        :splash_screen => current_user.splash_screen,
        :collapse_activities => !!current_user.settings["collapse_activities"]
      }.to_json
    end

    def json_people
      projects = {}
      current_user.people.all(:include => :project).collect do |p|
        projects[p.project.id] = {
          :permalink => p.project.permalink,
          :role => p.role,
          :name => h(p.project.name) }
      end
      projects.to_json
    end

end

app/views/users/form/_delete.haml
- if current_user.projects.count > 0
  %p= t('.steps_before_1')
  %p= t('.steps_before_2')
  %p= t('.steps_before_3')
- else
  %p= t('.what_will_happen')
  %p= link_to t('.delete_my_account'), destroy_user_path

app/views/users/form/_linked_accounts.haml
- if Teambox.config.providers? and !Teambox.config.providers.empty?
  - Teambox.config.providers.each do |provider|
    %p{:id => provider[:provider].downcase}
      - if current_user.app_links.find_by_provider(provider[:provider])
        = t(:'oauth.your_account_is_linked_html', :provider => provider[:provider].titleize)
        = link_to t(:'oauth.unlink_account'), unlink_app_path(provider[:provider])
      - else
        = t(:'oauth.your_account_is_not_linked_html', :provider => provider[:provider].titleize)
        = link_to t(:'oauth.link_account'), "#{OmniAuth.config.path_prefix}/#{provider[:provider]}"

app/views/users/form/_new.haml
- if @invitation_token
  = hidden_field_tag 'invitation', @invitation_token

.first_name.text_field
  = f.label :first_name, t('users.form.first_name')
  = f.text_field :first_name, :autofocus => 'autofocus'
  = errors_for user, :first_name
.last_name.text_field
  = f.label :last_name, t('users.form.last_name')
  = f.text_field :last_name
  = errors_for user, :last_name
.email.text_field
  = f.label :email, t('users.form.email')
  - if (@invitation || @app_link)
    = f.text_field :email, :readonly => 'readonly', :style => 'color: #999'
  - else
    = f.text_field :email
  = errors_for user, :email
- if @invitation
  .use_this_email{ :style => 'margin: 10px; padding: 10px; border: 1px rgb(220,220,150) solid; background-color: rgb(255,255,200)' }
    = t('.use_this_email')

.language.select
  = f.label :locale, t('users.form.language')
  = f.select :locale, locale_select_values

.time_zone.select
  = f.label :time_zone, t('users.form.time_zone')
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"

%fieldset.account
  %legend= t('.account.title')
  %p
    = t('.account.choose_username')
    %br
    = t('.account.validations')
  .login.text_field
    = f.label :login, t('users.form.login')
    = f.text_field :login
    = errors_for user, :login
  .password.text_field
    = f.label :password, t('users.form.password')
    = f.password_field :password, :autocomplete => 'off'
    = errors_for user, :password
  .password.text_field
    = f.label :password_confirmation, t('users.form.confirm_password')
    = f.password_field :password_confirmation, :autocomplete => 'off'
    = errors_for user, :password_confirmation

/ - build_user_phone_number(user)
/ - f.fields_for :card do |card|
/   - card.fields_for :phone_numbers do |phone|
/     .phone_number.text_field
/       = phone.label :name, t('users.form.phone')
/       = phone.text_field :name
/       .field_note= t('users.form.phone_for_integration')

app/views/users/form/_notifications.haml
.check_boxes.notifications
  %p= t('.clarification', :login => user.login)
  .check_box.notify
    = f.check_box :notify_conversations
    = f.label :notify_conversations, t('.notify_conversations')
  .check_box.notify
    = f.check_box :notify_tasks
    = f.label :notify_tasks, t('.notify_tasks')
  .check_box.notify
    = f.check_box :wants_task_reminder
    = f.label :wants_task_reminder, t('.wants_task_reminder')

app/views/users/form/_picture.haml
%p= t(user.avatar?? '.we_have_this_avatar_html' : '.gravatar_in_use_html', :gravatar => gravatar_url)
%p= t('.upload_here_or_at_gravatar_html', :gravatar => gravatar_url)
%p
  = f.label :avatar, t('.field')
  = f.file_field :avatar
- if user.avatar?
  %p
    = f.label :avatar_destroy, t('.destroy')
    = f.check_box :avatar_destroy

.your_avatars
  = image_tag avatar_or_gravatar(user, :profile)
  = image_tag avatar_or_gravatar(user, :thumb)
  = image_tag avatar_or_gravatar(user, :micro)

app/views/users/form/_profile.haml
.first_name.text_field
  = f.label :first_name, t('users.form.first_name')
  = f.text_field :first_name, :autofocus => 'autofocus'
  = errors_for user, :first_name
.last_name.text_field
  = f.label :last_name, t('users.form.last_name')
  = f.text_field :last_name
  = errors_for user, :last_name

.description.text_area
  = f.label :biography, t('users.form.biography')
  = f.text_area :biography

= list_card_fields(f,%w(phone_numbers email_addresses websites addresses ims social_networks))

app/views/users/form/_settings.haml
.login.text_field
  = f.label :login, t('users.form.login')
  = f.text_field :login
  = errors_for user, :login
.email.text_field
  = f.label :email, t('users.form.email')
  - if (@invitation || @app_link)
    = f.text_field :email, :readonly => 'readonly', :style => 'color: #999'
  - else
    = f.text_field :email
  = errors_for user, :email

#password_fields{ :style => 'display: none' }
  .password.text_field
    = f.label :old_password, t('users.form.old_password')
    = f.password_field :old_password, :autocomplete => 'off'
    = errors_for user, :old_password
  .password.text_field
    = f.label :password, t('users.form.password')
    = f.password_field :password, :autocomplete => 'off'
    = errors_for user, :password
  .password.text_field
    = f.label :password_confirmation, t('users.form.confirm_password')
    = f.password_field :password_confirmation, :autocomplete => 'off'
    = errors_for user, :password_confirmation

#change_password_link
  = link_to_function t('users.form.change_password'), show_user_password_fields

.first_day_of_week.select
  = f.label :first_day_of_week, t('users.form.first_day_of_week')
  = f.select :first_day_of_week, [[t('users.form.sunday'), 'sunday'],[t('users.form.monday'), 'monday']]
    
.language.select
  = f.label :locale, t('users.form.language')
  = f.select :locale, locale_select_values
  
.time_zone.select
  = f.label :time_zone, t('users.form.time_zone')
  = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"

.betatester.check_box
  = f.check_box :betatester
  = f.label :betatester, t('users.form.betatester'), :style => 'float: none'